version: '3.7'

services: 
    database:
        image: postgres:12
        restart: always
        ports:
            - "5433:5432"
        environment: 
            POSTGRES_DB: ppi
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
        volumes: 
            - viroshopdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - database
        ports:
            - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped

    # backend:
    #     ports:
    #         - 80:80
    #     links: 
    #         - database
    #     depends_on: 
    #         - database
    #     restart: unless-stopped
        

volumes:
    viroshopdata: